name: Test Bundle

on: [push, pull_request]

jobs:
  test_bundle:
    runs-on: ubuntu-latest
    name: test bundle
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test bundle
        uses: ./
        with:
          base-spec: test/petstore.yaml
          bundled-spec: test/petstore-bundled.yaml

      - name: check result
        run: |
          git diff --no-index test/petstore-bundled.yaml test/petstore.yaml
