name: Test Lint

on: [push, pull_request]

jobs:
  test_lint:
    runs-on: ubuntu-latest
    name: test lint
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test lint
        uses: ./
        with:
          args: lint test/petstore.yaml
